spring:
  application:
    name: dtidigital.testepratico
  docker:
    compose:
      file: docker-compose.dev.yml
  datasouce:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/encomendas
    user: 'dtidigital'
    password: 'password'
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true